# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/system_no_ila.xdc

# Block Designs: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_tdd_sync_0/system_util_ad9361_tdd_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_divclk_sel_0/system_util_ad9361_divclk_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_sel_0 || ORIG_REF_NAME==system_util_ad9361_divclk_sel_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_divclk_reset_0/system_util_ad9361_divclk_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_reset_0 || ORIG_REF_NAME==system_util_ad9361_divclk_reset_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_adc_fifo_0/system_util_ad9361_adc_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==system_util_ad9361_adc_fifo_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_adc_pack_0/system_util_ad9361_adc_pack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_pack_0 || ORIG_REF_NAME==system_util_ad9361_adc_pack_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_dac_fifo_0/system_axi_ad9361_dac_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_fifo_0 || ORIG_REF_NAME==system_axi_ad9361_dac_fifo_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_dac_upack_0/system_util_ad9361_dac_upack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_dac_upack_0 || ORIG_REF_NAME==system_util_ad9361_dac_upack_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_gpreg_0/system_axi_gpreg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpreg_0 || ORIG_REF_NAME==system_axi_gpreg_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_GND_1_0/system_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_xbar_0/system_axi_cpu_interconnect_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_imp_xbar_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_imp_xbar_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_3/system_axi_cpu_interconnect_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_3 || ORIG_REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_3} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_0/system_axi_cpu_interconnect_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_1/system_axi_cpu_interconnect_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_1 || ORIG_REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_1} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_2/system_axi_cpu_interconnect_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_2 || ORIG_REF_NAME==system_axi_cpu_interconnect_imp_auto_pc_2} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_gmii_to_rgmii_0_0/system_gmii_to_rgmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_gmii_to_rgmii_0_0 || ORIG_REF_NAME==system_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_sys_logic_inv_0/system_sys_logic_inv_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_logic_inv_0 || ORIG_REF_NAME==system_sys_logic_inv_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_divclk_sel_concat_0/system_util_ad9361_divclk_sel_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_sel_concat_0 || ORIG_REF_NAME==system_util_ad9361_divclk_sel_concat_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_btle_controller_0_0/system_btle_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_btle_controller_0_0 || ORIG_REF_NAME==system_btle_controller_0_0} -quiet] -quiet

# IP: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0} -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/bef3/up_xfer_cntrl_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/bef3/ad_rst_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/bef3/up_xfer_status_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/bef3/up_clock_mon_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_tdd_sync_0/util_tdd_sync_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_divclk_reset_0/system_util_ad9361_divclk_reset_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_reset_0 || ORIG_REF_NAME==system_util_ad9361_divclk_reset_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_util_ad9361_adc_fifo_0/util_wfifo_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==system_util_ad9361_adc_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_ad9361_dac_fifo_0/util_rfifo_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_fifo_0 || ORIG_REF_NAME==system_axi_ad9361_dac_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_gpreg_0/system_axi_gpreg_0_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpreg_0 || ORIG_REF_NAME==system_axi_gpreg_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_gpreg_0/bef3/ad_rst_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpreg_0 || ORIG_REF_NAME==system_axi_gpreg_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_3/system_axi_cpu_interconnect_imp_auto_pc_3_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_0/system_axi_cpu_interconnect_imp_auto_pc_0_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_1/system_axi_cpu_interconnect_imp_auto_pc_1_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_cpu_interconnect_imp_auto_pc_2/system_axi_cpu_interconnect_imp_auto_pc_2_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_gmii_to_rgmii_0_0/synth/system_gmii_to_rgmii_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_gmii_to_rgmii_0_0 || ORIG_REF_NAME==system_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_gmii_to_rgmii_0_0/synth/system_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_gmii_to_rgmii_0_0 || ORIG_REF_NAME==system_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_gmii_to_rgmii_0_0/synth/system_gmii_to_rgmii_0_0_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/ip/system_clk_wiz_1_0/system_clk_wiz_1_0_ooc.xdc

# XDC: /home/vishwaksen/pentarisc/projects/clash/BTLE/fpga/pr/src/system_ooc.xdc
